import type { NextPage } from "next"
import Head from "next/head"
import Footer from "../components/Footer/Footer"
import NavBar from "../components/NavBar/NavBar"
import styles from "../styles/Home.module.css"
import getGoogleOAuthURL from "../utils/getGoogleUri"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Content for Creators - iso201</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <a href={getGoogleOAuthURL()}>
          Login with Google
        </a>
      </main>
      <Footer />
    </div>
  )
}

export default Home
