import type { NextPage } from "next"
import Head from "next/head"
import Footer from "../components/Footer/Footer"
import NavBar from "../components/NavBar/NavBar"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Content for Creators</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
      </main>
      <Footer />
    </div>
  )
}

export default Home
